### ISSUE TITLE
Startup Error (ConfigError) on backend on a Raspberry Pi 4 

### ISSUE THREAD

**Issue by mxd1365** [asymworks/jadetree-backend#5]
After running the install process, the backend is failing to startup. Logs are attached.

I attempted a full reinstall (cloned repo again, docker-compose down). Same problem occurred.

[jadetree_error_log.log](https://github.com/asymworks/jadetree-backend/files/7471661/jadetree_error_log.log)

**Comment by asymworks** [comment]
Hi @mxd1365, thanks for the error report.  It looks like the Docker Compose and configuration files got outdated.  I just pushed a change and it works for me locally now.  Try a `git pull` and re-run the Docker Compose commands and see if that fixes it?

**Comment by mxd1365** [comment]
Everything seems great now. Thanks!
